---

- name: Create units directory
  ansible.builtin.file:
    path: "{{ vaultwarden_unit_path }}"
    state: directory
    owner: "{{ vaultwarden_user }}"
    group: "{{ vaultwarden_group }}"
    mode: u=rwx,g=rx,o=
    selevel: _default
    serole: _default
    setype: _default
    seuser: _default

- name: Copy container unit file
  ansible.builtin.template:
    src: vaultwarden.container.j2
    dest: "{{ vaultwarden_unit_path }}/vaultwarden.container"
    owner: "{{ vaultwarden_user }}"
    group: "{{ vaultwarden_group }}"
    mode: u=rw,g=r,o=
    selevel: _default
    serole: _default
    setype: _default
    seuser: _default

- name: Copy volume unit file
  ansible.builtin.template:
    src: vaultwarden.volume.j2
    dest: "{{ vaultwarden_unit_path }}/vaultwarden.volume"
    owner: "{{ vaultwarden_user }}"
    group: "{{ vaultwarden_group }}"
    mode: u=rw,g=r,o=
    selevel: _default
    serole: _default
    setype: _default
    seuser: _default

- name: Start container
  ansible.builtin.systemd:
    name: vaultwarden.service
    state: restarted
    enabled: true
    daemon_reload: true
    scope: user
  become: true
  become_user: "{{ vaultwarden_user }}"
