# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/9"
  config.vm.box_version = "3.0.0"
  config.vm.hostname = "vaultwarden.localhost"

  config.vm.network "private_network", ip: "10.255.0.10"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    dnf -y update
    dnf -y install podman
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible/vagrant_test.yml"
  end
end
